apiVersion: v1
kind: Service
metadata:
  namespace: paul
  name: simple-service
spec:
  selector:
    app: simple
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31129
