apiVersion: v1
kind: Namespace
metadata:
  name:  paul

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: paul
  name: simple-deployment
  labels:
    app: simple
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple
  template:
    metadata:
      namespace: paul
      labels:
        app: simple
    spec:
      containers:
      - name: simple
        image: psaltos/simple:2.0
        ports:
        - containerPort: 80
        env:
        - name: PRUEBA
          value: hola
        - name: NGINX_PORT
          value: "80"
        - name: PRUEBA_CONFIG
          valueFrom:
            configMapKeyRef:
              name: mi-configuracion
              key: limite-maximo
        - name: PRUEBA2_CONFIG
          valueFrom:
            configMapKeyRef:
              name: mi-configuracion
              key: limite-minimo
        - name: SECRETO
          valueFrom:
            secretKeyRef:
              name: mis-secretos
              key: password
        - name: ADMIN
          valueFrom:
            secretKeyRef:
              name: mis-secretos
              key: admin

---

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: paul
  name: mi-configuracion
  labels:
    app: simple
data:
  limite-maximo: "ilitimado"
  limite-minimo: "0"

---

# Codificar secretos con el commando:
# echo -n "secreto" | base64 -
apiVersion: v1
kind: Secret
metadata:
  namespace: paul
  name:  mis-secretos
  labels:
    app: simple
data:
  admin: YWRtaW5zZWNyZXRv
  password: MTIzNDU=
type: Opaque
