apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
  labels:
    app: simple
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple
  template:
    metadata:
      labels:
        app: simple
    spec:
      containers:
      - name: simple
        image: nginx:1.22.1
        ports:
        - containerPort: 80
        env:
        - name: PRUEBA
          value: hola
        - name: NGINX_PORT
          value: "80"
