apiVersion: apps/v1
kind: Deployment
metadata:
  name: tutorial-deployment
  namespace: nombre
  labels:
    app: tutorial
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tutorial
  template:
    metadata:
      namespace: nombre
      labels:
        app: tutorial
    spec:
      containers:
      - name: tutorial
        image: docker/getting-started:latest
        ports:
        - containerPort: 80
