apiVersion: v1
kind: Service
metadata:
  name: tutorial-service
  namespace: nombre
  labels:
     app: tutorial
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30003
    protocol: TCP
    name: http
  selector:
     app: tutorial
