apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-mapa-web-deployment
  labels:
    app: k8s-mapa-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-mapa-web
  template:
    metadata:
      labels:
        app: k8s-mapa-web
    spec:
      containers:
      - name: k8s-mapa-web
        image: psaltos/k8s-mapa-web:1.0
        ports:
        - containerPort: 80
